### ISSUE TITLE
Warning even if route settings are provided

### ISSUE THREAD

**Issue by mileswatson** [talbotp/serverless-apigateway-route-settings#1]
When I run "serverless package" or "serverless deploy", the extension throws the following warnings:

 - `Warning: No default Route Settings have been provided.`
 - `Warning: No Route settings have been provided.`

This is despite having included the following code in the `serverless.yml` file.
```
plugins:
  - serverless-apigateway-route-settings
custom:
  routeSettings:
    rateLimit: 10
    burstLimit: 5
    detailedMetricsEnabled: false
```

Curiously, the deployment seems to work as expected. I dug around a little bit, and found that the cloud formation code was correct. 

```
"HttpApiStage": {
  "Type": "AWS::ApiGatewayV2::Stage",
  "Properties": {
    "ApiId": {
      "Ref": "HttpApi"
    },
    "StageName": "$default",
    "AutoDeploy": true,
    "DefaultRouteSettings": {
      "DetailedMetricsEnabled": false,
      "ThrottlingBurstLimit": 5,
      "ThrottlingRateLimit": 10
    }
  }
},
```

The error is still thrown when overriding the settings for a specific function (and the corresponding cloud formation code is also correct).
