### ISSUE TITLE
Function `getRouteKey` does not find resource if http method is in lowercase

### ISSUE THREAD

**Issue by rion18** [talbotp/serverless-apigateway-route-settings#11]
**Brief explanation and reproducible example**

While `httpApi` in `events` allow for lowercase methods, it seems that this plugin does not.

Small reproducible example:

```yaml
functions:
  awesomeFunction:
    handler: src/myfunction.handler
    name: my-awesome-function
    events:
      - httpApi:
          method: post
          path: /my-awesome-function
          routeSettings:
            rateLimit: 10
            burstLimit: 5
```

**Actual result**

I would expect this plugin to update the `routeSettings` under `stage` in the Cloudformation template. Instead, I get a warning: 

```sh
Unable to update settings for post /my-awesome-function
```

**Expected result**
My Cloudformation template should have something of the sort:
```yaml
    "HttpApiStage": {
      "Type": "AWS::ApiGatewayV2::Stage",
      "Properties": {
        "ApiId": {
          "Ref": "HttpApi"
        },
        "StageName": "dev",
        "AutoDeploy": true,
        "DefaultRouteSettings": {
          "DetailedMetricsEnabled": false
        }
        "RouteSettings": {
          // content generated by this plugin
        }
      }
    },
```

**Proposed solution**

It would seem that a fix is simple, adding `toUppercase()` to the `RouteSettings` class. This would help NOT forcing the user to add uppercase http methods.
